language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19
android:
  components:
    - build-tools-19.0.0
    - android-19
sudo: false
script:
  - cd SSIDLogger;./gradlew assemble --stacktrace
  - ls -al SSIDLogger/build
  - ls -al SSIDLogger/build/apk
  - ls -al SSIDLogger/app/build/outputs/apk
