language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19
android:
  components:
    - build-tools-19.0.0
    - android-19
sudo: false
script:
  - cd SSIDLogger
  - gradle build
  - ls -al build
  - ls -al build/apk
