language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19
android:
  components:
    - platform-tools
    - tools
    - android-19
    - build-tools-22.0.1
    - extra-google-m2repository
    - extra-android-m2repository
sudo: false
script:
  - cd SSIDLogger
  - ./gradlew assemble --stacktrace
  - ../travis.sh
