language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19
android:
  components:
    - platform-tools
    - tools
    - android-19
    - extra-google-m2repository
    - extra-android-m2repository
sudo: false
script:
  - cd SSIDLogger;./gradlew assemble --stacktrace
  - ls -al SSIDLogger/build
  - ls -al SSIDLogger/build/apk
  - ls -al SSIDLogger/app/build/outputs/apk
